---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: webapp
  name: webapp
spec:
  replicas: 3
  selector:
    app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: webapp:local
        command: [ ./webapp.rb ]
        env:
        - name: CONJUR_APPLIANCE_URL
          value: https://conjur-master.conjur.svc.cluster.local/api
        - name: CONJUR_ACCOUNT
          value: dev
        - name: CONJUR_SSL_CERTIFICATE
          valueFrom:
            configMapKeyRef:
              name: webapp
              key: ssl-certificate
        - name: CONJUR_AUTHN_LOGIN
          value: host/conjur/openshift-12345/apps/webapp
        - name: CONJUR_AUTHN_API_KEY
          valueFrom:
            secretKeyRef:
              name: conjur-webapp-api-key
              key: api-key

